/* Add All Action constants here  */

const ACTION_TYPES = {
  SPLASH_LAUNCHED: 'SPLASH_LAUNCHED',
  FETCH_WEATHER: 'FETCH_WEATHER',
  ADD_WEATHER_SUCCESS: 'ADD_WEATHER_SUCCESS',
  ADD_WEATHER_FAILURE: 'ADD_WEATHER_FAILURE',
  ADD_WEATHER_STARTED: 'ADD_WEATHER_STARTED',
};

export { ACTION_TYPES };
